[package]
name = "redwood-wiki"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPLv3"
description = "SQLite-based knowledge base"

[dependencies]
chrono = "0.4.19"
log = "0.4.11"
fern = "0.6.0"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.5"
rusqlite = { version = "0.24.1", features = ["bundled"] }
pulldown-cmark = { version = "0.8.0", default-features = false }
syntect = "4.4.0"
