[package]
name = "redwood-wiki"
version = "0.1.0"
authors = ["Benjamin Richner"]
edition = "2018"
license = "GPL-3.0-only"
description = "SQLite-based knowledge base"
keywords = ["wiki", "knowledge-base"]
categories = ["text-processing", "web-programming"]
repository = "https://github.com/BenjaminRi/Redwood-Wiki"

[dependencies]
chrono = "0.4.19"
log = "0.4.11"
fern = "0.6.0"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.5"
rusqlite = { version = "0.24.1", features = ["bundled", "chrono"] }
pulldown-cmark = { version = "0.8.0", default-features = false }
syntect = "4.5.0"
